// template/react-vite/antd/src/views/home/index.tsx
import { Button } from 'antd'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
export default function Home() {
  const [count, setCount] = useState(0)
  const handleClick = () => {
    setCount(count + 1)
  }
  const navigate = useNavigate()
  const routerSwitch = (path: string) => {
    navigate(path)
  }
  return (
        <div className="card">
            <Button size="large" onClick={handleClick}>
                count is { count }
            </Button>
            <Button size="large" type="primary" onClick={() => routerSwitch('/hello')}>
                click to hello page
            </Button>
        </div>
  )
}

// template/vue-antd-windicss-vitest/src/views/home/index.vue
<script lang="ts" setup name="home">
import { useRouter } from 'vue-router'
import { ref } from 'vue'

const router = useRouter()
const count = ref(0)
</script>

<template>
  <div class="card">
    <a-button type="button" size="large" @click="count++">
      count is {{ count }}
    </a-button>
  </div>
  <a-button type="primary" @click="router.push('/hello')">
    click to hello page
  </a-button>
</template>

<style scoped lang="scss">
.card {
  margin: 10px 0;
}
</style>
